# Generated by Django 5.1.15 on 2026-07-27 12:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_student_route_supervisor_latitude_and_more'),
        ('tenancy', '0002_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_address', models.TextField(blank=True)),
                ('requested_area', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('is_read', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_requests', to='people.student')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
