# Generated by Django 5.1.15 on 2026-07-27 12:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_student_route_supervisor_latitude_and_more'),
        ('tenancy', '0002_school_latitude_school_longitude'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('breakdown', 'Breakdown'), ('off_route', 'Off route'), ('trip_started', 'Trip started'), ('delay', 'Delay'), ('completed', 'Completed'), ('parent_request', 'Parent request'), ('reminder', 'Reminder'), ('info', 'Info')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='people.student')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trips.trip')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverCheckIn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', max_length=16)),
                ('state', models.CharField(choices=[('no_response', 'No response'), ('pending', 'Pending'), ('checked_in', 'Checked in')], default='no_response', max_length=16)),
                ('checked_in_at', models.TimeField(blank=True, null=True)),
                ('pending_minutes', models.PositiveIntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='people.driver')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.school')),
            ],
            options={
                'ordering': ['state', 'driver__full_name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'driver', 'service_date', 'shift'), name='uniq_checkin_per_shift')],
            },
        ),
    ]
