# Generated by Django 5.1.15 on 2026-07-27 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('people', '0003_student_route_supervisor_latitude_and_more'),
        ('routing', '0001_initial'),
        ('tenancy', '0002_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', max_length=16)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_time', 'On-time'), ('delayed', 'Delayed'), ('off_route', 'Off-route'), ('broken_down', 'Broken down'), ('completed', 'Completed')], default='scheduled', max_length=16)),
                ('scheduled_departure', models.TimeField(blank=True, null=True)),
                ('actual_departure', models.TimeField(blank=True, null=True)),
                ('scheduled_arrival', models.TimeField(blank=True, null=True)),
                ('actual_arrival', models.TimeField(blank=True, null=True)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('current_stop_index', models.PositiveIntegerField(default=0)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.bus')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='people.driver')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='routing.route')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.school')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='people.supervisor')),
            ],
            options={
                'ordering': ['-service_date', 'route__code'],
            },
        ),
    ]
