# Generated by Django 5.1.15 on 2026-07-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_student_latitude_student_longitude'),
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='routing.route'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
