# Generated by Django 5.1.15 on 2026-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_student_route_supervisor_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='supervisors/'),
        ),
    ]
