# Generated by Django 5.1.15 on 2026-07-26 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bus_number', models.CharField(max_length=32)),
                ('license_plate', models.CharField(blank=True, max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('capacity', models.PositiveIntegerField(default=25)),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('maintenance', 'Maintenance'), ('issue', 'Issue')], default='in_service', max_length=16)),
                ('breakdown_reason', models.CharField(blank=True, max_length=120)),
                ('last_maintenance_at', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.school')),
            ],
            options={
                'ordering': ['bus_number'],
                'constraints': [models.UniqueConstraint(fields=('school', 'bus_number'), name='uniq_bus_number_per_school')],
            },
        ),
    ]
