# Generated by Django 5.1.15 on 2026-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='buses/'),
        ),
    ]
