/**
 * Style Dictionary config — emits the same token set to:
 *   - dist/tokens.css   (CSS custom properties, consumed by the web app / Tailwind)
 *   - dist/tokens.dart  (a Dart class, consumed by flutter_packages/busla_core)
 *   - dist/tokens.json  (flat reference)
 *
 * This is the single source that keeps web + mobile colours (and the status-colour
 * system) identical. Edit tokens/*.json, then `pnpm --filter @busla/tokens build`.
 */

/** Custom Dart format: a `BuslaTokens` class of `Color`/double constants. */
function dartFormatter({ dictionary }) {
  const toDart = (t) => {
    const name = t.path.join("_");
    const v = t.value;
    if (typeof v === "string" && v.startsWith("#")) {
      const hex = v.replace("#", "");
      const full = hex.length === 6 ? `FF${hex}` : hex;
      return `  static const Color ${name} = Color(0x${full.toUpperCase()});`;
    }
    if (typeof v === "string" && v.endsWith("px")) {
      return `  static const double ${name} = ${parseFloat(v)};`;
    }
    return `  static const String ${name} = ${JSON.stringify(v)};`;
  };
  const body = dictionary.allTokens.map(toDart).join("\n");
  return `// GENERATED by @busla/tokens — do not edit.\nimport 'dart:ui';\n\nclass BuslaTokens {\n  BuslaTokens._();\n${body}\n}\n`;
}

export default {
  source: ["tokens/**/*.json"],
  hooks: {
    formats: {
      "busla/dart": dartFormatter,
    },
  },
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "dist/",
      files: [
        { destination: "tokens.css", format: "css/variables", options: { outputReferences: true } },
      ],
    },
    json: {
      transformGroup: "js",
      buildPath: "dist/",
      files: [{ destination: "tokens.json", format: "json/flat" }],
    },
    dart: {
      transformGroup: "js",
      // Emit straight into the shared Flutter package so mobile is single-sourced too.
      buildPath: "../../flutter_packages/busla_core/lib/generated/",
      files: [{ destination: "tokens.dart", format: "busla/dart" }],
    },
  },
};
